name: PHP Lint & WP Standards

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  php-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, curl, json, xml

      - name: Install Composer Dependencies (Optional)
        run: |
          if [ -f composer.json ]; then
            composer install --no-interaction --no-progress --no-suggest
          fi

      - name: PHP Lint
        run: find . -name '*.php' -exec php -l {} \;

      - name: WordPress Coding Standards
        run: |
          if [ -d vendor/bin ]; then
            vendor/bin/phpcs --standard=WordPress ./ || true
          fi
